Repository vmware-samples/vcenter-event-broker-appliance, pull requests merged in 2020-04, with the labels that each got.

#67 Example gotag govmomi function
  examples/README.md
  examples/go/tagging/.gitignore
  examples/go/tagging/README.MD
  examples/go/tagging/handler/client.go
  examples/go/tagging/handler/go.mod
  examples/go/tagging/handler/go.sum
  examples/go/tagging/handler/handler.go
  examples/go/tagging/handler/handler_test.go
  examples/go/tagging/handler/testdata/event.json
  examples/go/tagging/handler/testdata/event2.json
  examples/go/tagging/handler/testdata/eventErr1.json
  examples/go/tagging/handler/testdata/eventErr2.json
  examples/go/tagging/handler/testdata/eventErr3.json
  examples/go/tagging/handler/testdata/eventErr4.json
  examples/go/tagging/handler/testdata/vcconfig.toml
  examples/go/tagging/handler/testdata/vcconfig2.toml
  examples/go/tagging/handler/testdata/vcconfigErr1.toml
  examples/go/tagging/handler/testdata/vcconfigErr2.toml
  examples/go/tagging/stack.yml
  examples/go/tagging/vcconfig.toml
Labels: documentation, enhancement

#105 Add Docker image for :VERSION tag
  vmware-event-router/Makefile
Labels: bug

#108 Consistent use of Notes in markdown files
  examples/go/tagging/README.MD
  examples/powercli/datastore-usage-email/README.md
  examples/powershell/vro/README.md
  examples/python/esx-mtu-fixer/README.md
  examples/python/tagging/README.MD
  getting-started-build.md
  getting-started.md
Labels: documentation

#113 Delete greetings workflow
  .github/workflows/greetings.yml
Labels: bug
