Repository vmware-samples/vcenter-event-broker-appliance, pull requests merged in 2020-10, with the labels that each got.

#206 Update build and README
  .gitignore
  vmware-event-router/Dockerfile
  vmware-event-router/README.MD
  vmware-event-router/cmd/router/main.go
  vmware-event-router/internal/config/v1alpha1/processor.go
  vmware-event-router/internal/integration/suite_aws_test.go
  vmware-event-router/internal/metrics/server.go
  vmware-event-router/internal/processor/aws_event_bridge.go
  vmware-event-router/internal/processor/aws_option.go
  vmware-event-router/internal/processor/openfaas.go
  vmware-event-router/internal/processor/openfaas_option.go
Labels: documentation

#223 Build development image on push
  .github/workflows/create-docker-dev-image.yml
Labels: enhancement

#207 Implement at-least-once delivery via checkpointing
  .gitignore
  vmware-event-router/.golangci.yml
  vmware-event-router/README.MD
  vmware-event-router/cmd/router/main.go
  vmware-event-router/deploy/event-router-config-aws.yaml
  vmware-event-router/deploy/event-router-config-openfaas.yaml
  vmware-event-router/go.mod
  vmware-event-router/go.sum
  vmware-event-router/internal/config/v1alpha1/provider.go
  vmware-event-router/internal/events/events.go
  vmware-event-router/internal/events/events_test.go
  vmware-event-router/internal/integration/openfaas_test.go
  vmware-event-router/internal/processor/processor.go
  vmware-event-router/internal/provider/provider.go
  vmware-event-router/internal/provider/vcenter.go
  vmware-event-router/internal/provider/vcenter/checkpoint.go
  vmware-event-router/internal/provider/vcenter/checkpoint_test.go
  vmware-event-router/internal/provider/vcenter/options.go
  vmware-event-router/internal/provider/vcenter/vcenter.go
  vmware-event-router/internal/provider/vcenter_option.go
  vmware-event-router/routerconfig.schema.json
Labels: documentation, enhancement

#236 Remove set-env references
  vmware-event-router/hack/run_integration_tests.sh
Labels: security

#212 Fix Docker proxy issue
  files/setup-01-os.sh
Labels: bug

#240 Fix lock in vcenter
  vmware-event-router/internal/provider/vcenter/vcenter.go
Labels: bug
