Repository vmware-samples/vcenter-event-broker-appliance, pull requests merged in 2020-12, with the labels that each got.

#255 Add Knative Processor
  vmware-event-router/README.MD
  vmware-event-router/cmd/router/main.go
  vmware-event-router/deploy/event-router-config-knative.yaml
  vmware-event-router/deploy/event-router-k8s.yaml
  vmware-event-router/go.mod
  vmware-event-router/go.sum
  vmware-event-router/internal/config/v1alpha1/config.go
  vmware-event-router/internal/config/v1alpha1/processor.go
  vmware-event-router/internal/config/v1alpha1/provider.go
  vmware-event-router/internal/processor/aws/aws_event_bridge.go
  vmware-event-router/internal/processor/knative/knative.go
  vmware-event-router/internal/processor/knative/options.go
  vmware-event-router/internal/processor/openfaas/openfaas.go
  vmware-event-router/internal/provider/vcenter/vcenter.go
  vmware-event-router/internal/provider/vcsim/vcsim.go
  vmware-event-router/routerconfig.schema.json
Labels: documentation, enhancement

#267 Integrate Knative processor into VEBA
  docs/_data/default.yml
  docs/kb/install-knative.md
  files/setup-05-event-processor.sh
  files/setup.sh
  manual/photon.xml.template
  scripts/photon-settings.sh
Labels: enhancement

#274 Add OVF dropdown for Knative processor selection
  manual/photon.xml.template
Labels: bug

#275 Fix metadata in Helm Chart
  vmware-event-router/chart/Chart.yaml
  vmware-event-router/chart/config.yaml
  vmware-event-router/chart/releases/event-router-v0.4.2-devel.tgz
Labels: bug

#278 Bump OpenFaaS SDK version
  vmware-event-router/go.mod
  vmware-event-router/go.sum
Labels: enhancement
