Repository vmware-samples/vcenter-event-broker-appliance, pull requests merged in 2020-06, with the labels that each got.

#166 Decouple from types.BaseEvent
  .gitignore
  vmware-event-router/Makefile
  vmware-event-router/cmd/main.go
  vmware-event-router/go.mod
  vmware-event-router/go.sum
  vmware-event-router/internal/connection/connection.go
  vmware-event-router/internal/events/events.go
  vmware-event-router/internal/events/events_test.go
  vmware-event-router/internal/metrics/metrics.go
  vmware-event-router/internal/metrics/server.go
  vmware-event-router/internal/processor/aws_event_bridge.go
  vmware-event-router/internal/processor/aws_event_bridge_test.go
  vmware-event-router/internal/processor/aws_option.go
  vmware-event-router/internal/processor/openfaas.go
  vmware-event-router/internal/processor/openfaas_option.go
  vmware-event-router/internal/processor/processor.go
  vmware-event-router/internal/stream/fake/vcenter_fake.go
  vmware-event-router/internal/stream/fake/vcenter_fake_test.go
  vmware-event-router/internal/stream/stream.go
  vmware-event-router/internal/stream/vcenter.go
  vmware-event-router/internal/stream/vcenter_option.go
Labels: enhancement

#169 Update Docker images used in VMware Event Router
  vmware-event-router/Dockerfile
Labels: important

#176 Updating docs to reflect changes with Proxy and SSH
  docs/kb/install-eventbridge.md
  docs/kb/install-openfaas.md
Labels: documentation

#174 Github Issue Templates for VEBA Bug Report and Feature Enhancements
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-enhancement.md
Labels: enhancement
