Repository vmware-samples/vcenter-event-broker-appliance, pull requests merged in 2020-05, with the labels that each got.

#116 Document deploying VEBA as K8s App
  vmware-event-router/hack/README.md
  vmware-event-router/hack/create_k8s_config.sh
  vmware-event-router/hack/example1.png
  vmware-event-router/hack/example2.png
Labels: documentation

#118 Add Github Action to push Docker Images
  .github/create-docker-release.yml
Labels: enhancement

#119 Move release workflow to right folder
  .github/workflows/create-docker-release.yml
Labels: bug

#121 Replace static VEBA text with dynamic DCUI interface
  files/setup-09-banner.sh
  files/veba-dcui
  licenses/github.com/gizak/termui/LICENSE
  licenses/github.com/shirou/gopsutil/LICENSE
  photon-version.json
  photon.json
  scripts/photon-settings.sh
  test/deploy_veba_openfaas_processor.sh
Labels: enhancement

#124 Remove unnecessary vmw:ExtraConfig from OVA
  manual/add_ovf_properties.sh
Labels: enhancement

#129 Add Github Action for Docker Pre-Release
  .github/workflows/create-docker-prerelease.yml
Labels: enhancement

#130 Add Action to reject PRs against master
  .github/workflows/protect-master.yml
Labels: enhancement

#131 Add Action for Event Router Unit Tests on PRs
  .github/workflows/router-unit-tests.yml
Labels: enhancement

#137 Updated docs to reflect new v0.4 path to event-router-config.json
  docs/kb/troubleshoot-appliance.md
Labels: documentation

#142 Added recommendation to add appliance IP to NO_PROXY
  manual/photon.xml.template
Labels: enhancement

#144 Fixed typo in processing ESCAPED_AWS_EVENTBRIDGE_EVENT_BUS variable
  files/setup-05-event-processor.sh
Labels: bug

#148 Add Action to block PR merge when title is WIP
  .github/workflows/check-wip-pr.yml
Labels: enhancement

#151 fix broken link
  docs/kb/contribute-functions.md
Labels: documentation

#152 install gems only for the user, and set a vendor path for bundle use
  docs/README.md
Labels: documentation

#164 Update Linter and Unit Test Action
  .github/workflows/router-unit-tests.yml
  vmware-event-router/Dockerfile
Labels: enhancement
