Repository vmware-samples/vcenter-event-broker-appliance, pull requests merged in 2021-05, with the labels that each got.

#374 Refactor Ingress Configuration based on Processor Type
  files/eventbridge-ingressroute-gateway.yaml
  files/knative-embedded-ingressroute-gateway.yaml
  files/knative-embedded-veba-ui-ingressroute-gateway.yaml
  files/knative-external-ingressroute-gateway.yaml
  files/openfaas-ingressroute-gateway.yaml
  files/setup-09-ingress.sh
  photon.json
Labels: bug

#385 Add support for custom VEBA TLS Certificate
  files/setup-09-ingress.sh
  files/setup.sh
  manual/photon.xml.template
Labels: enhancement

#387 Configure Docker Container Log Rotation + Sed Fix
  files/setup-01-os.sh
  files/setup-09-ingress.sh
Labels: bug, enhancement

#380 Example Knative PowerShell Email Function
  examples/knative/powershell/kn-ps-email/Dockerfile
  examples/knative/powershell/kn-ps-email/README.md
  examples/knative/powershell/kn-ps-email/email_secret.json
  examples/knative/powershell/kn-ps-email/function.yaml
  examples/knative/powershell/kn-ps-email/handler.ps1
  examples/knative/powershell/kn-ps-email/screenshots/screenshot-1.png
  examples/knative/powershell/kn-ps-email/server.ps1
  examples/knative/powershell/kn-ps-email/test/docker-test-env-variable
  examples/knative/powershell/kn-ps-email/test/send-cloudevent-test.ps1
  examples/knative/powershell/kn-ps-email/test/send-cloudevent-test.sh
  examples/knative/powershell/kn-ps-email/test/test-payload.json
Labels: documentation

#391 Add issue greeting
  .github/comment-template.md
  .github/workflows/issue-greeting.yml
Labels: enhancement

#392 Add Helm Chart for Knative
  .github/workflows/router-verify-helm.yml
  vmware-event-router/README.MD
  vmware-event-router/chart/Chart.yaml
  vmware-event-router/chart/config.yaml
  vmware-event-router/chart/releases/event-router-v0.6.2-pre-release.tgz
  vmware-event-router/chart/releases/event-router-v0.6.2.tgz
  vmware-event-router/chart/templates/100_clusterrolebinding.yaml
  vmware-event-router/chart/templates/200_serviceaccount.yaml
  vmware-event-router/chart/templates/300_secret.yaml
  vmware-event-router/chart/templates/400_deployment.yaml
  vmware-event-router/chart/templates/500_service.yaml
  vmware-event-router/chart/values.yaml
Labels: documentation, enhancement

#389 Update documentation to reflect new TLS certificate replacement in VEBA
  docs/kb/advanced-certificates.md
Labels: documentation

#399 Document Trusted Root Certificate support w/VMware Event Router
  docs/kb/advanced-certificates.md
Labels: documentation

#403 fix: Update documentation to reflect minimum vCenter 7.0 for VEBA UI
  docs/kb/install-knative.md
Labels: documentation

#405 fix: Fix command in adding trusted root CA cert documentation
  docs/kb/advanced-certificates.md
Labels: documentation

#415 chore: Daily build and helm verification
  .github/workflows/router-verify-build.yml
  .github/workflows/router-verify-helm.yml
Labels: enhancement

#413 feat: Add Knative PowerCLI vSphere Tagging Example
  docs/site/examples-knative.md
  examples/knative/powercli/kn-pcli-tag/Dockerfile
  examples/knative/powercli/kn-pcli-tag/README.md
  examples/knative/powercli/kn-pcli-tag/function.yaml
  examples/knative/powercli/kn-pcli-tag/handler.ps1
  examples/knative/powercli/kn-pcli-tag/tag_secret.json
  examples/knative/powercli/kn-pcli-tag/test/docker-test-env-variable
  examples/knative/powercli/kn-pcli-tag/test/send-cloudevent-test.ps1
  examples/knative/powercli/kn-pcli-tag/test/send-cloudevent-test.sh
  examples/knative/powercli/kn-pcli-tag/test/test-payload.json
Labels: documentation

#417 feat: Add Knative Base PowerShell/PowerCLI Container Images
  examples/knative/templates/Dockerfile.pcli
  examples/knative/templates/Dockerfile.ps
  examples/knative/templates/README.md
  examples/knative/templates/server.ps1
Labels: documentation, enhancement
