Repository vmware-samples/vcenter-event-broker-appliance, pull requests merged in 2021-09, with the labels that each got.

#560 Apply server.ps1 fixes to all PS/CLI container images
  examples/knative/powercli/kn-pcli-tag/Dockerfile
  examples/knative/powercli/kn-pcli-tag/README.md
  examples/knative/powercli/kn-pcli-tag/function.yaml
  examples/knative/powershell/kn-ps-echo/Dockerfile
  examples/knative/powershell/kn-ps-echo/README.md
  examples/knative/powershell/kn-ps-echo/function.yaml
  examples/knative/powershell/kn-ps-email/Dockerfile
  examples/knative/powershell/kn-ps-email/README.md
  examples/knative/powershell/kn-ps-email/function.yaml
  examples/knative/powershell/kn-ps-slack-vsphere-alarm/Dockerfile
  examples/knative/powershell/kn-ps-slack-vsphere-alarm/README.md
  examples/knative/powershell/kn-ps-slack-vsphere-alarm/function.yaml
  examples/knative/powershell/kn-ps-slack/Dockerfile
  examples/knative/powershell/kn-ps-slack/README.md
  examples/knative/powershell/kn-ps-slack/function.yaml
  examples/knative/templates/Dockerfile.pcli
  examples/knative/templates/Dockerfile.ps
  examples/knative/templates/README.md
Labels: bug

#571 Update OVF labels with deprecated event processors
  manual/photon.xml.template
Labels: enhancement

#576 Update Fluentbit config using YTT overlay
  files/configs/fluentbit/templates/fluentbit-configmap-template.yaml
  files/downloads/fluentbit/overlay.yaml
  files/setup-011-fluentbit.sh
Labels: bug

#575 Correct execption message for TAG_SECRET not being defined
  examples/knative/powercli/kn-pcli-tag/handler.ps1
Labels: bug

#592 Prevent $ char from being eval in escaped variables
  files/setup.sh
Labels: bug

#587 Update Github Photon OS badge to 4.0
  README.md
Labels: documentation

#597 Update PS/PCLI images with latest server.ps1 fixes
  examples/knative/powercli/kn-pcli-tag/Dockerfile
  examples/knative/powercli/kn-pcli-tag/function.yaml
  examples/knative/powershell/kn-ps-echo/Dockerfile
  examples/knative/powershell/kn-ps-echo/function.yaml
  examples/knative/powershell/kn-ps-email/Dockerfile
  examples/knative/powershell/kn-ps-email/function.yaml
  examples/knative/powershell/kn-ps-slack-vsphere-alarm/Dockerfile
  examples/knative/powershell/kn-ps-slack-vsphere-alarm/function.yaml
  examples/knative/powershell/kn-ps-slack/Dockerfile
  examples/knative/powershell/kn-ps-slack/function.yaml
  examples/knative/templates/Dockerfile.pcli
  examples/knative/templates/README.md
Labels: enhancement

#599 Update kn-ps-slack with try/catch
  examples/knative/powershell/kn-ps-slack/handler.ps1
Labels: enhancement

#585 Add notification example using Telegram
  docs/site/examples-knative.md
  examples/knative/powercli/kn-pcli-telegram/Dockerfile
  examples/knative/powercli/kn-pcli-telegram/README.md
  examples/knative/powercli/kn-pcli-telegram/function.yaml
  examples/knative/powercli/kn-pcli-telegram/handler.ps1
  examples/knative/powercli/kn-pcli-telegram/screenshots/screenshots-01.png
  examples/knative/powercli/kn-pcli-telegram/telegram_secret.json
  examples/knative/powercli/kn-pcli-telegram/test/docker-test-env-variable
  examples/knative/powercli/kn-pcli-telegram/test/send-cloudevent-test.ps1
  examples/knative/powercli/kn-pcli-telegram/test/send-cloudevent-test.sh
  examples/knative/powercli/kn-pcli-telegram/test/test-payload.json
Labels: enhancement

#584 Add PowerShell SMS example using Twillo
  docs/site/examples-knative.md
  examples/knative/powershell/kn-ps-twillio-sms/Dockerfile
  examples/knative/powershell/kn-ps-twillio-sms/README.md
  examples/knative/powershell/kn-ps-twillio-sms/function.yaml
  examples/knative/powershell/kn-ps-twillio-sms/handler.ps1
  examples/knative/powershell/kn-ps-twillio-sms/screenshots/screenshot-1.png
  examples/knative/powershell/kn-ps-twillio-sms/sms_secret.json
  examples/knative/powershell/kn-ps-twillio-sms/test/docker-test-env-variable
  examples/knative/powershell/kn-ps-twillio-sms/test/send-cloudevent-test.ps1
  examples/knative/powershell/kn-ps-twillio-sms/test/send-cloudevent-test.sh
  examples/knative/powershell/kn-ps-twillio-sms/test/test-payload.json
Labels: enhancement

#600 Add VMware Horizon Slack example function
  docs/site/examples-knative.md
  examples/knative/powershell/kn-ps-horizon-login-slack/Dockerfile
  examples/knative/powershell/kn-ps-horizon-login-slack/README.md
  examples/knative/powershell/kn-ps-horizon-login-slack/function.yaml
  examples/knative/powershell/kn-ps-horizon-login-slack/handler.ps1
  examples/knative/powershell/kn-ps-horizon-login-slack/screenshots/screenshot-01.png
  examples/knative/powershell/kn-ps-horizon-login-slack/slack_secret.json
  examples/knative/powershell/kn-ps-horizon-login-slack/test/docker-test-env-variable
  examples/knative/powershell/kn-ps-horizon-login-slack/test/send-cloudevent-test.ps1
  examples/knative/powershell/kn-ps-horizon-login-slack/test/send-cloudevent-test.sh
  examples/knative/powershell/kn-ps-horizon-login-slack/test/test-payload.json
Labels: enhancement

#601 Updated description for VEBA in Docs
  README.md
  docs/_data/default.yml
  docs/kb/intro-about.md
  docs/kb/intro-architecture.md
  docs/kb/intro-event-router.md
  docs/kb/use-horizon-events.md
  docs/kb/use-vcenter-events.md
Labels: documentation

#602 Add VMware Cloud Notification Gateway example using Slack
  docs/site/examples-knative.md
  examples/knative/powershell/kn-ps-ngw-slack/Dockerfile
  examples/knative/powershell/kn-ps-ngw-slack/README.md
  examples/knative/powershell/kn-ps-ngw-slack/function.yaml
  examples/knative/powershell/kn-ps-ngw-slack/handler.ps1
  examples/knative/powershell/kn-ps-ngw-slack/screenshots/screenshot-01.png
  examples/knative/powershell/kn-ps-ngw-slack/slack_secret.json
  examples/knative/powershell/kn-ps-ngw-slack/test/docker-test-env-variable
  examples/knative/powershell/kn-ps-ngw-slack/test/send-cloudevent-test.ps1
  examples/knative/powershell/kn-ps-ngw-slack/test/send-cloudevent-test.sh
  examples/knative/powershell/kn-ps-ngw-slack/test/test-payload.json
Labels: enhancement

#609 Updated VEBA Appliance deployment guides
  docs/kb/install-eventbridge.md
  docs/kb/install-knative.md
  docs/kb/install-openfaas.md
Labels: documentation

#606 Add webhook function to ingress custom events
  docs/site/examples-knative.md
  examples/knative/powershell/kn-ps-webhook/Dockerfile
  examples/knative/powershell/kn-ps-webhook/README.md
  examples/knative/powershell/kn-ps-webhook/function.yaml
  examples/knative/powershell/kn-ps-webhook/handler.ps1
  examples/knative/powershell/kn-ps-webhook/screenshots/screenshot-01.png
  examples/knative/powershell/kn-ps-webhook/screenshots/screenshot-02.png
  examples/knative/powershell/kn-ps-webhook/server.ps1
  examples/knative/powershell/kn-ps-webhook/test/docker-test-env-variable
  examples/knative/powershell/kn-ps-webhook/test/send-local-webhook-test.ps1
  examples/knative/powershell/kn-ps-webhook/test/send-local-webhook-test.sh
  examples/knative/powershell/kn-ps-webhook/test/send-webhook-to-veba.sh
  examples/knative/powershell/kn-ps-webhook/test/test-payload.json
  examples/knative/powershell/kn-ps-webhook/webhook_secret.json
Labels: enhancement

#603 Add VMware Cloud Notification Gateway example using Microsoft Teams
  docs/site/examples-knative.md
  examples/knative/powershell/kn-ps-ngw-teams/Dockerfile
  examples/knative/powershell/kn-ps-ngw-teams/README.md
  examples/knative/powershell/kn-ps-ngw-teams/function.yaml
  examples/knative/powershell/kn-ps-ngw-teams/handler.ps1
  examples/knative/powershell/kn-ps-ngw-teams/screenshots/screenshot-01.png
  examples/knative/powershell/kn-ps-ngw-teams/teams_secret.json
  examples/knative/powershell/kn-ps-ngw-teams/test/docker-test-env-variable
  examples/knative/powershell/kn-ps-ngw-teams/test/send-cloudevent-test.ps1
  examples/knative/powershell/kn-ps-ngw-teams/test/send-cloudevent-test.sh
  examples/knative/powershell/kn-ps-ngw-teams/test/test-payload.json
Labels: enhancement

#612 Updated Getting Started Guide w/Knative
  docs/kb/contribute-start.md
Labels: documentation

#608 Update Router and Best Practices Documentation
  docs/kb/contribute-eventrouter.md
  docs/kb/contribute-functions.md
  docs/kb/intro-event-router.md
  docs/kb/use-eventspec.md
  vmware-event-router/README.MD
Labels: documentation

#614 fix: Fix settings process exit code in server.ps1
  examples/knative/templates/server.ps1
  examples/knative/templates/test/process-init-error-handler.ps1
  examples/knative/templates/test/server-test-helper.ps1
  examples/knative/templates/test/server.tests.ps1
Labels: bug

#621 Updated VEBA timeline with v0.7 release
  docs/site/evolutions.md
Labels: documentation

#619 Simplify docs testing/contribution using Jekyll Docker image
  docs/README.md
  docs/kb/contribute-site.md
Labels: documentation

#626 Update PS/PCLI images w/latest CE SDK/PowerCLI versions
  examples/knative/powercli/kn-pcli-tag/Dockerfile
  examples/knative/powercli/kn-pcli-tag/function.yaml
  examples/knative/powercli/kn-pcli-telegram/Dockerfile
  examples/knative/powercli/kn-pcli-telegram/function.yaml
  examples/knative/powershell/kn-ps-echo/Dockerfile
  examples/knative/powershell/kn-ps-echo/function.yaml
  examples/knative/powershell/kn-ps-email/Dockerfile
  examples/knative/powershell/kn-ps-email/function.yaml
  examples/knative/powershell/kn-ps-horizon-login-slack/Dockerfile
  examples/knative/powershell/kn-ps-horizon-login-slack/function.yaml
  examples/knative/powershell/kn-ps-ngw-slack/Dockerfile
  examples/knative/powershell/kn-ps-ngw-slack/function.yaml
  examples/knative/powershell/kn-ps-ngw-teams/Dockerfile
  examples/knative/powershell/kn-ps-ngw-teams/function.yaml
  examples/knative/powershell/kn-ps-slack-vsphere-alarm/Dockerfile
  examples/knative/powershell/kn-ps-slack-vsphere-alarm/function.yaml
  examples/knative/powershell/kn-ps-slack/Dockerfile
  examples/knative/powershell/kn-ps-slack/function.yaml
  examples/knative/powershell/kn-ps-twillio-sms/Dockerfile
  examples/knative/powershell/kn-ps-twillio-sms/function.yaml
  examples/knative/powershell/kn-ps-webhook/Dockerfile
  examples/knative/powershell/kn-ps-webhook/function.yaml
  examples/knative/powershell/kn-ps-webhook/server.ps1
  examples/knative/templates/Dockerfile.pcli
  examples/knative/templates/Dockerfile.ps
  examples/knative/templates/README.md
Labels: enhancement

#628 Add Scheduled VM Snapshot Retention using PingSource Function Example
  docs/site/examples-knative.md
  examples/knative/powercli/kn-pcli-snapshot-cron/Dockerfile
  examples/knative/powercli/kn-pcli-snapshot-cron/README.md
  examples/knative/powercli/kn-pcli-snapshot-cron/function.yaml
  examples/knative/powercli/kn-pcli-snapshot-cron/handler.ps1
  examples/knative/powercli/kn-pcli-snapshot-cron/snapshot_secret.json
  examples/knative/powercli/kn-pcli-snapshot-cron/test/docker-test-env-variable
  examples/knative/powercli/kn-pcli-snapshot-cron/test/send-cloudevent-test.ps1
  examples/knative/powercli/kn-pcli-snapshot-cron/test/send-cloudevent-test.sh
  examples/knative/powercli/kn-pcli-snapshot-cron/test/test-payload.json
Labels: documentation, enhancement

#636 fix: Prevent duplicate Processor entries in /etc/veba-release
  files/setup-06-event-processor.sh
Labels: bug
