Repository vmware-samples/vcenter-event-broker-appliance, pull requests merged in 2021-04, with the labels that each got.

#328 Integrate VEBA UI
  files/setup-010-veba-ui.sh
  files/setup-011-banner.sh
  files/setup-05-knative.sh
  files/setup-06-event-processor.sh
  files/setup-09-ingress.sh
  files/setup.sh
  manual/photon.xml.template
  photon.json
  veba-bom.json
Labels: enhancement

#333 Disable digest checking for Harbor Registry
  files/setup-05-knative.sh
Labels: bug

#334 Integrate Sockeye into VEBA
  files/setup-05-knative.sh
  files/setup-09-ingress.sh
  veba-bom.json
Labels: enhancement

#338 Add `/events` API endpoint
  docs/kb/img/veba-appliance-diagram.png
  docs/kb/img/veba-architecture.png
Labels: documentation

#339 Fixed VEBA UI image + Documentation Updates
  docs/kb/intro-functions.md
  docs/kb/use-functions.md
  docs/site/examples-knative.md
  examples/knative/powershell/kn-ps-echo/README.md
  examples/knative/powershell/kn-ps-echo/function.yaml
  examples/knative/powershell/kn-ps-slack/README.md
  examples/knative/powershell/kn-ps-slack/function.yaml
  veba-bom.json
Labels: bug, documentation

#341 Fix typo for Docker push command
  examples/knative/powershell/kn-ps-echo/README.md
  examples/knative/powershell/kn-ps-slack/README.md
Labels: documentation

#344 Re-enable Knative Serving registry digest check
  files/setup-05-knative.sh
Labels: bug

#345 Adding missing vmware-functions NS to secret example
  examples/knative/powershell/kn-ps-slack/README.md
Labels: documentation

#348 Clarifying Knative OVF description + Docs
  docs/kb/install-knative.md
  manual/photon.xml.template
Labels: documentation, enhancement

#351 Add Windows specific Docker command to kn-ps-slack function
  examples/knative/powershell/kn-ps-slack/README.md
Labels: documentation

#353 Remove * in front of Closes keyword + Fix Typo in PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#363 Document minimum vSphere Privileges for VEBA UI
  docs/kb/install-knative.md
Labels: documentation

#368 Update the correct cert name for TLS replacement
  docs/kb/advanced-certificates.md
Labels: documentation

#373 Add correct AWS Event Bridge Type into Event Router Config
  files/setup-06-event-processor.sh
  vmware-event-router/deploy/event-router-config-aws.yaml
Labels: bug, documentation

#376 VEBA UI fix for incorrect TLS miss-match
  veba-bom.json
Labels: bug
