Repository vmware-samples/vcenter-event-broker-appliance, pull requests merged in 2022-02, with the labels that each got.

#774 docs: Update event router config path
  docs/kb/advanced-certificates.md
  docs/kb/troubleshoot-appliance.md
Labels: documentation

#756 PowerCLI example function for Distributed Virtual Switch config
  examples/knative/powercli/kn-pcli-vds-config/Dockerfile
  examples/knative/powercli/kn-pcli-vds-config/README.md
  examples/knative/powercli/kn-pcli-vds-config/function.yaml
  examples/knative/powercli/kn-pcli-vds-config/handler.ps1
  examples/knative/powercli/kn-pcli-vds-config/test/docker-test-env-variable
  examples/knative/powercli/kn-pcli-vds-config/test/send-cloudevent-test.ps1
  examples/knative/powercli/kn-pcli-vds-config/test/send-cloudevent-test.sh
  examples/knative/powercli/kn-pcli-vds-config/test/test-payload.json
  examples/knative/powercli/kn-pcli-vds-config/vds_secret.json
Labels: documentation, enhancement

#775 Create Knative PowerCLI template
  docs/kb/contribute-functions.md
  examples/knative/powercli/kn-pcli-template/Dockerfile
  examples/knative/powercli/kn-pcli-template/README.md
  examples/knative/powercli/kn-pcli-template/function.yaml
  examples/knative/powercli/kn-pcli-template/function_secret.json
  examples/knative/powercli/kn-pcli-template/handler.ps1
  examples/knative/powercli/kn-pcli-template/test/docker-test-env-variable
  examples/knative/powercli/kn-pcli-template/test/send-cloudevent-test.ps1
  examples/knative/powercli/kn-pcli-template/test/send-cloudevent-test.sh
  examples/knative/powercli/kn-pcli-template/test/test-payload.json
Labels: documentation

#787 Slack Function enhancement: event agnostic + customized message
  examples/knative/powershell/kn-ps-slack/README.md
  examples/knative/powershell/kn-ps-slack/function.yaml
  examples/knative/powershell/kn-ps-slack/handler.ps1
  examples/knative/powershell/kn-ps-slack/slack_secret.json
  examples/knative/powershell/kn-ps-slack/test/docker-test-env-variable
Labels: enhancement

#789 Update to Photon OS 4.0 Rev2
  photon-version.json
  scripts/photon-settings.sh
Labels: chore

#777 Remove OpenFaaS links from website
  docs/_includes/site-header.html
  docs/index.html
  docs/kb/advanced-deploy-k8s.md
  docs/kb/img/veba-secret-ui-1.png
  docs/kb/img/veba-secret-ui-2.png
  docs/kb/intro-functions.md
  docs/kb/use-functions.md
  docs/site/faq.md
Labels: documentation

#798 Ensure RabbitMQ image is pre-pulled
  files/configs/knative/templates/rabbit-template.yaml
  files/setup-05-knative.sh
  veba-bom.json
Labels: bug

#801 Add pause container 3.5
  veba-bom.json
Labels: bug

#805 Update Envoy to listen on 80/443
  files/downloads/knative-contour/overlay.yaml
Labels: bug
