Repository vmware-samples/vcenter-event-broker-appliance, pull requests merged in 2023-03, with the labels that each got.

#1018 fix: Replace spaces with dash in Github Action Id
  .github/workflows/verify-gcr-login.yaml
Labels: bug

#1021 fix: Update Github Action id with valid string
  .github/workflows/gcr-dev-image.yml
  .github/workflows/gcr-prerelease-image.yml
  .github/workflows/release.yml
  .github/workflows/verify-gcr-login.yaml
Labels: bug

#1022 chore: Update Go deps
  vmware-event-router/go.mod
  vmware-event-router/go.sum
Labels: dco-required

#1026 docs: Added v0.7.5 updates to VEBA Evolution timeline
  docs/site/evolutions.md
Labels: documentation

#1024 docs: Update Resource page with latest VEBA content
  docs/_data/resources.yml
Labels: documentation
