Repository vmware-samples/vcenter-event-broker-appliance, pull requests merged in 2024-02, with the labels that each got.

#1157 Update README file according to VEBA v0.8 changes
  README.md
  vmware-event-router/README.MD
Labels: documentation

#1161 Fix wrong md formatting in README
  README.md
Labels: bug, documentation

#1164 update all veba core-components to a higher version
  docs/site/evolutions.md
  scripts/photon-settings.sh
  veba-bom.json
Labels: important, dependencies

#1168 Add new wait condition to setup-05-knative.sh
  files/setup-05-knative.sh
Labels: dependencies

#1170 feat: Re-order Knative deployment based on Knative E2E testing
  files/setup-05-knative.sh
Labels: enhancement

#1173 fix: Update /etc/veba-release to include Knative processor entry
  files/setup-07-event-router-webhook.sh
  scripts/photon-settings.sh
Labels: bug

#1174 chore: Cleanup unused GH workflows
  .github/workflows/router-helm.yml
Labels: chore
