Repository vmware-samples/vcenter-event-broker-appliance, pull requests merged in 2024-01, with the labels that each got.

#1149 feat: Google Chat Notification function
  examples/knative/powershell/kn-ps-google-chat/Dockerfile
  examples/knative/powershell/kn-ps-google-chat/README.md
  examples/knative/powershell/kn-ps-google-chat/function.yaml
  examples/knative/powershell/kn-ps-google-chat/google_chat_secret.json
  examples/knative/powershell/kn-ps-google-chat/handler.ps1
  examples/knative/powershell/kn-ps-google-chat/test/docker-test-env-variable
  examples/knative/powershell/kn-ps-google-chat/test/send-cloudevent-test.ps1
  examples/knative/powershell/kn-ps-google-chat/test/send-cloudevent-test.sh
  examples/knative/powershell/kn-ps-google-chat/test/test-payload.json
Labels: enhancement

#1150 fix: Default to JSON payload encoding for Tanzu Sources
  files/configs/horizon-source/templates/horizon-source-template.yml
  files/configs/vsphere-source/templates/vsphere-source-template.yml
Labels: bug

#1151 fix: Update Tag Attach/Detach func to type filter
  examples/knative/powercli/kn-pcli-nsx-tag-sync/function.yaml
Labels: bug

#1153 Major updates on website and documentation for v0.8
  docs/_config.yml
  docs/_data/default.yml
  docs/_data/team.yml
  docs/index.html
  docs/kb/advanced-certificates.md
  docs/kb/contribute-appliance.md
  docs/kb/contribute-eventrouter.md
  docs/kb/contribute-functions.md
  docs/kb/contribute-site.md
  docs/kb/contribute-start.md
  docs/kb/deploy-event-router-kind.md
  docs/kb/deploy-tanzu-sources-kind.md
  docs/kb/function-tutorial-deploy.md
  docs/kb/function-tutorial-intro.md
  docs/kb/function-tutorial-modtest.md
  docs/kb/img/kn-ps-slack-alert3.png
  docs/kb/img/kn-ps-slack-events.png
  docs/kb/img/sockeye.png
  docs/kb/img/veba-architecture.png
  docs/kb/img/veba-sockeye-events.png
  docs/kb/img/veba-sockeye-poweredoff-event.png
  docs/kb/img/veba-sockeye-poweredon-event.png
  docs/kb/install-knative.md
  docs/kb/install-veba.md
  docs/kb/intro-about.md
  docs/kb/intro-architecture.md
  docs/kb/intro-event-router.md
  docs/kb/intro-functions.md
  docs/kb/intro-tanzu-sources.md
  docs/kb/private-registry.md
  docs/kb/troubleshoot-appliance.md
  docs/kb/troubleshoot-functions.md
  docs/kb/use-eventspec.md
  docs/kb/use-functions.md
  docs/site/community.md
  docs/site/evolutions.md
  docs/site/examples.md
  docs/site/faq.md
Labels: documentation, important
